### ISSUE TITLE
Can't start containers / Button not present

### ISSUE THREAD

**Issue by Chocobean** [neu-solarwinds/CTFd-with-docker-plugin#1]
Tried to use this, as I have some problems with another version.

Everything runs smoothly, but I can't see the Button to start the container in the challenges.

Any Idea perhaps?

**Comment by diptendukar** [comment]
Can you post a screenshot perhaps. I was having the same problem in this version - https://github.com/phannhat17/CTFd-Docker-Plugin . I could invoke the containers from js console using container_run(ID). Hence I changed the jquery to normal javascript and then front-end buttons can be seen.

**Comment by diptendukar** [comment]
make a hacky fix to view.html. Check and see if that works.

**Comment by Chocobean** [comment]
Seems to be working. Thanks
